PaginaWebOxxo/PaginaWebOxxo/Pages/CanjeRecompensas.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PaginaWebOxxo.Pages;

public class CanjeRecompensasModel : PageModel
{

    public void OnGet()
    {

    }
}

PaginaWebOxxo/PaginaWebOxxo/Pages/Capacitaciones.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PaginaWebOxxo.Model;

namespace PaginaWebOxxo.Pages;

public class CapacitacionesModel : PageModel
{
    public List<NivelUsuario> Progresos { get; set; }
    private readonly DataBaseContext _context;

    public CapacitacionesModel(DataBaseContext context)
    {
        _context = context;
    }
    public Usuarios Usuario {get; set;}


    public void OnGet()
    {
        int numEmpleado = (int)HttpContext.Session.GetInt32("numEmpleado");
        var db = new DataBaseContext();
        Progresos = db.ObtenerProgresoPorEmpleado(numEmpleado);
        Usuario = _context.ObtenerUsuarioPorEmpleados(numEmpleado);
    }

    public string ObtenerPorcentajeBarra(int estrellas)
    {
        return $"{(estrellas / 3.0) * 100}%";
    }

    public List<bool> ObtenerEstadoEstrellas(int estrellas)
    {
        return Enumerable.Range(1, 3).Select(i => i <= estrellas).ToList();
    }
}

PaginaWebOxxo/PaginaWebOxxo/Pages/DashboardAsesor.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PaginaWebOxxo.Model;

namespace PaginaWebOxxo.Pages;

public class DashboardAsesorModel : PageModel
{
    private readonly DataBaseContext _context;

    public DashboardAsesorModel(DataBaseContext context)
    {
        _context = context;
    }

    [BindProperty]
    public string asesor { get; set; }

    public string Url { get; set; }

    public void OnGet()
    {
        int numEmpleado = (int)HttpContext.Session.GetInt32("numEmpleado");
        asesor = numEmpleado.ToString();
        Url = ActualizarUrl(asesor);

    }

    private string ActualizarUrl(string asesor)
    {
        return $"https://lookerstudio.google.com/embed/reporting/acd411a9-8da9-4dff-87af-ed879643abf2/page/wg4MF?params=%7B%22asesor_param1%22:%22{asesor}%22%2C%22asesor_param2%22:%22{asesor}%22%2C%22asesor_param3%22:%22{asesor}%22%2C%22asesor_param4%22:%22{asesor}%22%2C%22asesor_param5%22:%22{asesor}%22%2C%22asesor_param6%22:%22{asesor}%22%7D";
    }
}

PaginaWebOxxo/PaginaWebOxxo/Pages/Empleados.cshtml.cs
using PaginaWebOxxo.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;
using System.Text.Json;

namespace PaginaWebOxxo.Pages;

public class EmpleadosModel : PageModel
{

    private readonly DataBaseContext _context;
    public EmpleadosModel(DataBaseContext context)
    {
        _context = context;
    }

    public Usuarios Lider { get; set; }
    public List<Usuarios> ListaEmpleados { get; set; }
    public List<Usuarios> ListaEmpleadosNoAsignados { get; set; }

    [BindProperty] public string numLider { get; set; }
    [BindProperty] public string numEmpleado { get; set; }

    public void OnGet()
    {
        int numLider = (int)HttpContext.Session.GetInt32("numEmpleado");

        Lider = _context.ObtenerUsuarioPorEmpleados(numLider);
        Lider.ColorEstatus = ObtenerColorEstatus(Lider.IdEstatus);

        ListaEmpleados = _context.ObtenerEmpleadosPorLider(numLider);
        foreach (var empleado in ListaEmpleados)
        {
            empleado.ColorEstatus = ObtenerColorEstatus(empleado.IdEstatus);
        }

        ListaEmpleadosNoAsignados = _context.ObtenerEmpleadosNoAsignados(numLider);
    }

    private string ObtenerColorEstatus(int idEstatus)
    {
        return idEstatus switch
        {
            1 => "bg-success",   
            2 => "bg-warning",   
            3 => "bg-danger",   
        };
    }

    public IActionResult OnPostEditarLider(int numEmpleado)
    {
        return Redirect($"Lider?numEmpleado={numEmpleado}");
    }

    public IActionResult OnPostEditarEmpleado(int NumEmpleado)
    {
        return Redirect($"Lider?numEmpleado={NumEmpleado}");
    }

    public IActionResult OnPostAgregarEmpleado(int numLider, int numEmpleado)
    {
        _context.AgregarEmpleado(numLider, numEmpleado);
        return Redirect($"Empleados?");
    }
}

PaginaWebOxxo/PaginaWebOxxo/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PaginaWebOxxo.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

PaginaWebOxxo/PaginaWebOxxo/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using PaginaWebOxxo.Model;

namespace PaginaWebOxxo.Pages
{
    public class IndexModel : PageModel
    {
        private readonly DataBaseContext _context;

        public IndexModel(DataBaseContext context)
        {
            _context = context;
        }

        [BindProperty]
        [Required(ErrorMessage = "Debes ingresar tu número de empleado.")]
        public int? NumEmpleado { get; set; }

        [BindProperty]
        [Required(ErrorMessage = "Debes ingresar la contraseña.")]
        public string Contraseña { get; set; }

        private Usuarios Usuario { get; set; }

        public void OnGet()
        {
            HttpContext.Session.Clear();
        }

        public IActionResult OnPostVerificarContraseña()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            
            var datosLogin = _context.login(NumEmpleado.Value);
            if (datosLogin != null && datosLogin.Contraseña == Contraseña)
            {
                HttpContext.Session.SetInt32("numEmpleado", NumEmpleado.Value);
                Usuario = _context.ObtenerUsuarioPorEmpleados(NumEmpleado.Value);
                HttpContext.Session.SetInt32("IdTipoPuesto", Usuario.IdTipoPuesto);
                if (Usuario.IdTipoPuesto == 2)
                {
                    return Redirect($"DashboardAsesor?numEmpleado={NumEmpleado.Value}");
                }
                else
                {
                    return Redirect($"Inicio?numEmpleado={NumEmpleado.Value}");
                }
            }
            else
            {
                ModelState.AddModelError("Contraseña", "Contraseña o número de empleado incorrectos. Inténtalo de nuevo.");
                return Page();
            }
        }
    }
}

PaginaWebOxxo/PaginaWebOxxo/Pages/Inicio.cshtml.cs
using PaginaWebOxxo.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Linq;

namespace PaginaWebOxxo.Pages
{
    public class InicioModel : PageModel
    {
        public int EmpleadoId { get; set; }
        private readonly DataBaseContext _context;

        public InicioModel(DataBaseContext context)
        {
            _context = context;
        }

        public Estadisticas EstadisticasUsuario { get; set; }
        public Usuarios Usuario { get; set; }
        public int TotalEstrellas { get; set; }

        [BindProperty]
        public int? numEmpleado { get; set; } 

        public void OnGet(int? numEmpleado)
        {

            int empleadoId = numEmpleado ?? HttpContext.Session.GetInt32("numEmpleado") ?? 0;

            HttpContext.Session.SetInt32("numEmpleado", empleadoId);

            EmpleadoId = empleadoId;

            EstadisticasUsuario = _context.ObtenerMonedasPorEmpleado(empleadoId);
            Usuario = _context.ObtenerUsuarioPorEmpleados(empleadoId);

            var progresos = _context.ObtenerProgresoPorEmpleado(empleadoId);
            TotalEstrellas = progresos.Sum(p => p.Estrellas);
        }
    }
}

PaginaWebOxxo/PaginaWebOxxo/Pages/Instrucciones.cshtml.cs
using PaginaWebOxxo.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;

namespace PaginaWebOxxo.Pages;

public class InstruccionesModel : PageModel
{
    private readonly DataBaseContext _context;


    public InstruccionesModel(DataBaseContext context)
    {
        _context = context;
    }

    public List<InstruccionVideojuego> Instrucciones { get; set; }

    public void OnGet()
    {
        Instrucciones = _context.ObtenerTodasLasInstrucciones();
    }
    public void OnPost()
    {
        Instrucciones = _context.ObtenerTodasLasInstrucciones();
    }
    
    
    
}

PaginaWebOxxo/PaginaWebOxxo/Pages/Lider.cshtml.cs
using PaginaWebOxxo.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;

namespace PaginaWebOxxo.Pages;

public class LiderModel : PageModel
{
    private readonly DataBaseContext _context;


    public LiderModel(DataBaseContext context)
    {
        _context = context;
    }

    [BindProperty]
    public string Telefono { get; set; }

    public Estadisticas estadisticas { get; set; }

    public Usuarios Usuario { get; set; }

    public Contacto contacto { get; set; }

    [BindProperty]
    public int? numEmpleado { get; set; }

    public void OnGet(int? numEmpleado)
    {

        int empleadoId;

        if (numEmpleado.HasValue)
        {
            empleadoId = numEmpleado.Value;
        }
        else
        {
            empleadoId = HttpContext.Session.GetInt32("numEmpleado") ?? 0;
            HttpContext.Session.SetInt32("numEmpleado", empleadoId);
        }

        contacto = _context.ObtenerContactoPorEmpleados(empleadoId);
        Usuario = _context.ObtenerUsuarioPorEmpleados(empleadoId);
        estadisticas = _context.ObtenerEstadisticasPorEmpleado(empleadoId);
        
    }

    public void OnPostActualizar(int? numEmpleado)
    {
        int empleadoId = numEmpleado ?? HttpContext.Session.GetInt32("numEmpleado") ?? 0;

        if (!numEmpleado.HasValue)
        {
            HttpContext.Session.SetInt32("numEmpleado", empleadoId);
        }

        if (string.IsNullOrEmpty(Telefono) || Telefono.Length != 10)
        {
            ModelState.AddModelError("Telefono", "El número de teléfono es inválido, debe contener 10 dígitos");
            contacto = _context.ObtenerContactoPorEmpleados(empleadoId);
            Usuario = _context.ObtenerUsuarioPorEmpleados(empleadoId);
            estadisticas = _context.ObtenerEstadisticasPorEmpleado(empleadoId);
            return;
        }


        _context.ActualizarTelefono(empleadoId, Telefono);

        contacto = _context.ObtenerContactoPorEmpleados(empleadoId);
        Usuario = _context.ObtenerUsuarioPorEmpleados(empleadoId);
        estadisticas = _context.ObtenerEstadisticasPorEmpleado(empleadoId);
    }
}

PaginaWebOxxo/PaginaWebOxxo/Pages/Personaje.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PaginaWebOxxo.Model;

namespace PaginaWebOxxo.Pages;

public class PersonajeModel : PageModel
{
    private readonly DataBaseContext _context;
    public PersonajeModel(DataBaseContext context)
    {
        _context = context;
    }

    public Usuarios Lider { get; set; }
    public string PersonajeSeleccionado { get; set; }
    public string TrackSeleccionado { get; set; }

    public void OnGet(string personaje = null, string track = null)
{
    int numEmpleado = (int)HttpContext.Session.GetInt32("numEmpleado");
    Lider = _context.ObtenerUsuarioPorEmpleados(numEmpleado);

    PersonajeSeleccionado = personaje ?? _context.ObtenerNombrePersonajeEquipado(numEmpleado);

    TrackSeleccionado = track ?? _context.ObtenerNombreTrackEquipado(numEmpleado);
}

    public IActionResult OnPostEquiparPersonaje(string personaje)
    {
        int numEmpleado = (int)HttpContext.Session.GetInt32("numEmpleado");
    
        int id = _context.ObtenerIdPersonalizacion(personaje);
    
        if (id > 0)
        {
            _context.EquiparPersonaje(numEmpleado, id);
        }

        return RedirectToPage(new { personaje = personaje, track = TrackSeleccionado });
    }
    

    public IActionResult OnPostEquiparTrack(string track)
    {
        int numEmpleado = (int)HttpContext.Session.GetInt32("numEmpleado");

        int id2 = _context.ObtenerIdPersonalizacionMusica(track);

        if (id2 > 0)
        {
            _context.EquiparTrack(numEmpleado, id2);
        }

        return RedirectToPage("Personaje", new { personaje = PersonajeSeleccionado, track = track });
    }

}

PaginaWebOxxo/PaginaWebOxxo/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PaginaWebOxxo.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

PaginaWebOxxo/PaginaWebOxxo/Pages/CanjeRecompensas.cshtml
@page
@model CanjeRecompensasModel
@{
    ViewData["Title"] = "Zona de Canje";
}
<body>
    <h1 class="text-center">@ViewData["Title"]</h1>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <h2 class="text-center">Proximamente</h2>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="text-center">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Oxxo_Logo.svg/2560px-Oxxo_Logo.svg.png" width="187px"/>
    </div>
</body>

PaginaWebOxxo/PaginaWebOxxo/Pages/DashboardAsesor.cshtml
@page
@model DashboardAsesorModel
@{
    ViewData["Title"] = "Estadísticas de Líderes de Tienda";
}

<body>
    <h1 class="color_letras cal-sans-regular">@ViewData["Title"]</h1><br>
    <iframe width="100%" height="1300" src="@Model.Url" frameborder="0" style="border:0" allowfullscreen sandbox="allow-storage-access-by-user-activation allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox"></iframe>
</body>

PaginaWebOxxo/PaginaWebOxxo/Pages/Empleados.cshtml
@page
@model EmpleadosModel
@{
    ViewData["Title"] = "Gestión de Empleados";
}

<body class="container-fluid px-5">
    <h1 class="color_letras cal-sans-regular">@ViewData["Title"]</h1><br>

    <div class="row align-items-center justify-content-between mb-4 py-4 text-center">
        <div class="col-md-5 color_letras cal-sans-regular fs-3">Empleado</div>
        <div class="col-md-2 color_letras cal-sans-regular fs-3">Horario</div>
        <div class="col-md-2 color_letras cal-sans-regular fs-3">Estatus</div>
        <div class="col-md-2 color_letras cal-sans-regular fs-3">Editar</div>
    </div>

    <div class="row align-items-center justify-content-between mb-4 py-4">
        <div class="col-md-5 d-flex align-items-center">
            <img src="@Model.Lider.fotoPerfil" alt="Foto de Trabajador" class="rounded-circle me-3 img-perfil" width="150" height="150">
            <div>
                <h3 class="fs-2 cal-sans-regular">@Model.Lider.Nombre @Model.Lider.ApellidoP</h3>
                <p class="fs-3 text-muted">@Model.Lider.Puesto</p>
            </div>
        </div>
        <div class="col-md-2 text-md-center fs-4">
            @Model.Lider.horarioInicio.ToString(@"hh\:mm") - @Model.Lider.horarioFin.ToString(@"hh\:mm")
        </div>
        <div class="col-md-2 d-flex align-items-center justify-content-center">
            <div class="estatus-circulo @Model.Lider.ColorEstatus"></div>
        </div>
        <div class="col-md-2 text-center">
            <form method="post" asp-page-handler="EditarLider">
                <input type="hidden" name="numEmpleado" value="@Model.Lider.NumEmpleado" />
                <button type="submit" class="btn btn-secondary rounded-circle p-3">
                    <i class="fa-solid fa-pencil fs-4"></i>
                </button>
            </form>
        </div>
    </div>

    @foreach (var empleado in Model.ListaEmpleados)
    {
        <div class="row align-items-center justify-content-between mb-4 py-4">
            <div class="col-md-5 d-flex align-items-center">
                <img src="@empleado.fotoPerfil"
                     alt="Foto de Trabajador" class="rounded-circle me-3 img-perfil" width="150" height="150">
                <div>
                    <h3 class="fs-2 cal-sans-regular">@empleado.Nombre @empleado.ApellidoP</h3>
                    <p class="fs-3 text-muted">@empleado.Puesto</p>
                </div>
            </div>
            <div class="col-md-2 text-md-center fs-4">
                @empleado.horarioInicio.ToString(@"hh\:mm") - @empleado.horarioFin.ToString(@"hh\:mm")
            </div>
            <div class="col-md-2 d-flex align-items-center justify-content-center">
                <div class="estatus-circulo @empleado.ColorEstatus"></div>
            </div>
            <div class="col-md-2 text-center">
                <form method="post" asp-page-handler="EditarEmpleado">
                    <input type="hidden" name="NumEmpleado" value="@empleado.NumEmpleado" />
                    <button type="submit" class="btn btn-secondary rounded-circle p-3">
                        <i class="fa-solid fa-pencil fs-4"></i>
                    </button>
                </form>
            </div>
        </div>
    }<br>

    <div class="row align-items-center justify-content-between mb-4 py-4">
        <div class="col-md-3 text-md-center">
            @if (Model.Lider.IdTipoPuesto == 1) 
            {
                <button class="btn btn-secondary w-100 boton-redondo fs-3 cal-sans-regular text-white" data-bs-toggle="modal" data-bs-target="#empleadoModal">Asignar empleado</button>
            }
        </div>

        <div class="col-md-3 d-flex align-items-center justify-content-center gap-3 fs-4">
            <span class="color_letras cal-sans-regular">Activo</span>
            <div class="circulo bg-success"></div>
        </div>
        <div class="col-md-3 d-flex align-items-center justify-content-center gap-3 fs-4">
            <span class="color_letras cal-sans-regular">Inactivo</span>
            <div class="circulo bg-warning"></div>
        </div>
        <div class="col-md-3 d-flex align-items-center justify-content-center gap-3 fs-4">
            <span class="color_letras cal-sans-regular">Ausente</span>
            <div class="circulo bg-danger"></div>
        </div>
    </div>

    <div class="modal fade" id="empleadoModal" aria-labelledby="empleadoModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <form method="post" asp-page-handler="AgregarEmpleado">
                    <div class="modal-header">
                        <h3 class="fs-2 cal-sans-regular">Agregar Empleado</h3>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" name="numLider" value="@Model.Lider.NumEmpleado" />
                        <div class="mb-3">
                            <select asp-for="numEmpleado" class="form-select form-select-lg">
                            @foreach (var empleado in Model.ListaEmpleadosNoAsignados)
                            {
                                <option value="@empleado.NumEmpleado">@empleado.Nombre @empleado.ApellidoP - @empleado.NumEmpleado</option>
                            }
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="row w-100">
                            <div class="col-6">
                                <button type="submit" class="btn btn-primary w-100">Agregar</button>
                            </div>
                            <div class="col-6">
                                <button type="button" class="btn btn-secondary w-100" data-bs-dismiss="modal">Cancelar</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

PaginaWebOxxo/PaginaWebOxxo/Pages/Personaje.cshtml
@page
@model PersonajeModel
@{
    ViewData["Title"] = "Personalización y Canje";
}

<body>
    <div>
        <button class="botonayuda" title="Para saber más de Oxxo clickea aquí" onclick="window.open('https://www.oxxo.com/','_blank')"><i class="fa-solid fa-question"></i></button>
    </div>
    <div class="layout-principal">
    <div class="columna-izquierda">
        <h1 class="color_letras cal-sans-regular">@ViewData["Title"]</h1><br>
        <div class="d-flex contenedor2">
            <img src="@Model.Lider.fotoPerfil" alt="Foto de Trabajador" class="rounded-circle me-3" width="150" height="150">
            <div>
                <h3 class="fs-2 cal-sans-regular">@Model.Lider.Nombre @Model.Lider.ApellidoP</h3>
                <p class="fs-3 text-muted">@Model.Lider.Puesto</p>
            </div>
            </figure>
        </div>
        <br>
        <br>
        <h3>Elegir Personaje</h3>
        <br>
        <div class="contenedor">
          <form method="post" asp-page-handler="EquiparPersonaje" class="elemento">
              <input type="hidden" name="personaje" value="JEFE" />
              <button type="submit" class=" @(Model.PersonajeSeleccionado == "JEFE" ? "seleccionado" : "")">
                  <div style="display: flex; flex-direction: column; align-items: center;">
                      <img src="imagenes/Personaje3PW.png" alt="">
                      <p style="font-size:25px; color: #000000;">JEFE</p>
                  </div>
              </button>
          </form>
          <form method="post" asp-page-handler="EquiparPersonaje" class="elemento">
              <input type="hidden" name="personaje" value="ALEX" />
              <button type="submit" class="@(Model.PersonajeSeleccionado == "ALEX" ? "seleccionado" : "")">
                  <div style="display: flex; flex-direction: column; align-items: center;">
                      <img src="imagenes/Personaje2PW.png" alt="">
                      <p style="font-size:25px; color: #000000;">ALEX</p>
                  </div>
              </button>
          </form>
          <form method="post" asp-page-handler="EquiparPersonaje" class=" elemento">
              <input type="hidden" name="personaje" value="ADAM" />
              <button type="submit" class="@(Model.PersonajeSeleccionado == "ADAM" ? "seleccionado" : "")">
                  <div style="display: flex; flex-direction: column; align-items: center;">
                      <img src="imagenes/Personaje4PW.png" alt="">
                      <p style="font-size:25px; color: #000000;">ADAM</p>
                  </div>
              </button>
          </form>
          <form method="post" asp-page-handler="EquiparPersonaje" class="elemento">
              <input type="hidden" name="personaje" value="AMELIA" />
              <button type="submit" class="@(Model.PersonajeSeleccionado == "AMELIA" ? "seleccionado" : "")">
                  <div style="display: flex; flex-direction: column; align-items: center;">
                      <img src="imagenes/Personaje1PW.png" alt="">
                      <p style="font-size:25px; color: #000000;">AMELIA</p>
                  </div>
              </button>
          </form>
        </div>
    </div>

    <div class="columna-derecha">
        <div>
        <h3>Elegir Música del Menú</h3>
        <br>
          <div class="contenedor3">
              <form method="post" asp-page-handler="EquiparTrack" class="elemento">
                  <input type="hidden" name="track" value="TRACK1" />
                  <button type="submit" class="@(Model.TrackSeleccionado == "TRACK1" ? "seleccionado" : "")">
                      <div style="display: flex; flex-direction: column; align-items: center;">
                          <img src="imagenes/Cancion.png" alt="" class="imagenes-musica">
                          <p style="font-size: 20px; color: #000000;">Pista 1</p>
                      </div>
                  </button>
              </form>
                <form method="post" asp-page-handler="EquiparTrack" class="elemento">
                    <input type="hidden" name="track" value="TRACK2" />
                    <button type="submit" class="@(Model.TrackSeleccionado == "TRACK2" ? "seleccionado" : "")">
                        <div style="display: flex; flex-direction: column; align-items: center;">
                            <img src="imagenes/Cancion.png" alt="" class="imagenes-musica">
                            <p style="font-size: 20px; color: #000000;">Pista 2</p>
                        </div>
                    </button>
                </form>
                <form method="post" asp-page-handler="EquiparTrack" class="elemento">
                    <input type="hidden" name="track" value="TRACK3" />
                    <button type="submit" class="@(Model.TrackSeleccionado == "TRACK3" ? "seleccionado" : "")">
                        <div style="display: flex; flex-direction: column; align-items: center;">
                            <img src="imagenes/Cancion.png" alt="" class="imagenes-musica">
                            <p style="font-size: 20px; color: #000000;">Pista 3</p>
                        </div>
                    </button>
                </form>
          </div>
        </div>

        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>

        <div>
        <h3>Recompensas</h3>
        <br>
        <br>
        <ul>
            <li>
              <button type="button" class="fs-3 custom-link-button" style="background:none; border:none; cursor:pointer;"  onclick="location.href='CanjeRecompensas'">Solicita Tiempo Aire</button>
            </li>
            <br>
            <br>
            <li>
              <button type="button" class="fs-3 custom-link-button" style="background:none; border:none; cursor:pointer;"  onclick="location.href='CanjeRecompensas'"> Canjea por Puntos Spin</button>
            </li>
            <br>
            <br>
            <li>
              <button type="button" class="fs-3 custom-link-button" style="background:none; border:none; cursor:pointer;"  onclick="location.href='CanjeRecompensas'">Obten Cupones</button>
            </li>
        </ul>
        </div>
    </div>
</div>

<div class="modal fade" id="empleadoModal" tabindex="-1" aria-labelledby="empleadoModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content text-center p-4">
      <div class="modal-header border-0 justify-content-center">
        <div class="bg-success bg-gradient text-white rounded-circle d-flex align-items-center justify-content-center" style="width: 60px; height: 60px;">
          <i class="bi bi-check-lg fs-2"></i>
        </div>
      </div>
      <div class="modal-body">
        <h5 class="modal-title mb-3" id="empleadoModalLabel">¡Cambio exitoso!</h5>
        <p class="mb-0">Ahora puedes ingresar al juego con tus cambios realizados.</p>
      </div>
    </div>
  </div>
</div>
</body>